---
title: "4 color problem"
author: "Chao XIA"
date: "02/20/2019"
output: pdf_document
editor_options: 
  chunk_output_type: console
---
## Descrption
Using Simulated Annealing to solve 4 color problem.

## General Idea
To count the mininum of mistakes made in the color of map.

Changing Baseline: Change the color of places made the most mistakes.

## Code
```{r}
# define the palette
mapcolor <- rainbow(4)
palette(mapcolor)

# install necessary package
  library("sp")
  library("maptools")
  library("plyr")
  # install.packages("spdep")
  library("spdep")

# set relative path
setwd(choose.dir()) # there will be three map files for this work.

# read map
chinamap <- readShapePoly("bou2_4p.shp")
proj4string(chinamap) <- "+proj=longlat +datum=WGS84"

# make a new map only have province data
chinamap <- chinamap[chinamap$AREA>0.1,]
chinamap <- chinamap[-which(chinamap$ADCODE99 == 130000)[2],]
chinamapdata <- chinamap@data

# get coordinates for provinces
map_crd <- coordinates(chinamap)

# Construct the spatial weight matrix
w_cn <- poly2nb(chinamap,queen = T) # automatically make the spatial matrix

## Add connection that cannot be made by the function 
w_cn[[31]] <- c(which(chinamapdata$ADCODE99 == 440000))
w_cn[[30]] <- sort(c(which(chinamapdata$ADCODE99 == 440000), which(chinamapdata$ADCODE99 == 330000), which(chinamapdata$ADCODE99 == 350000)))
w_cn[[which(chinamapdata$ADCODE99 == 440000)]] <- as.integer(sort(c(w_cn[[which(chinamapdata$ADCODE99 == 440000)]], 30,31)))
w_cn[[which(chinamapdata$ADCODE99 == 330000)]] <- as.integer(sort(c(w_cn[[which(chinamapdata$ADCODE99 == 330000)]], 30)))
w_cn[[which(chinamapdata$ADCODE99 == 350000)]] <- as.integer(sort(c(w_cn[[which(chinamapdata$ADCODE99 == 350000)]], 30)))

w_cn_mat <- nb2listw(w_cn, style="W", zero.policy=TRUE) # construct spatial weight matrix

plot(chinamap)
points(map_crd[,c(1,2)], col = "red", pch = "*")
plot(w_cn_mat, coords = map_crd, pch = 19, cex = 0.1, col = "blue", add = T) # proved w_cn's relationship is right
```
```{r}
# Count the mistakes seperately and totally
Counting <- function(colormethod){
  R <- numeric() # store the mistakes
  
  for(place in 1:length(w_cn)){
    
    listofneighbour <- w_cn[[place]] # Find the neighbours of this place
    
    mistake <- 0 # Initialize the mistake of the color of this place
    
    for(i in listofneighbour){
      if(colormethod[place] == colormethod[i]){
        mistake <- mistake + 1
      }
    }
    R[place] <- mistake # count the mistakes of the place
  }
  
  return(c(R, sum(R)))
}
```
```{r}
# Define stimualted annealing function
four_color_problem <- function(Startcolor, InitialTemp, FinalTemp, TempDecreaseRate){
  Temp <- InitialTemp
  
  chinamapcolor <- Startcolor
  
  R <- Counting(chinamapcolor)
  
  plot(chinamap, col = chinamapcolor)
  for(n in 1:(nrow(map_crd)-1)){
    points(map_crd[[n,1]],map_crd[[n,2]] , col = "black", pch = as.character(R[n]), lwd = 2)
  }
  points(map_crd[[nrow(map_crd),1]]+1, map_crd[[nrow(map_crd),2]]-1, col = "black", pch = as.character(R[nrow(map_crd)]), lwd = 2)
  legend("topleft", legend = c("total", R[length(R)]), bty = "n")
  
  
  
  while (Temp > FinalTemp){  # we keep going until things cool down
  
    newchinamapcolor <- numeric()
    
    change <- max(R[-length(R)])
    for(i in 1:nrow(map_crd)){
      if(R[i] == change){
        newchinamapcolor[i] <- sample(1:4,1)
      }else{
        newchinamapcolor[i] <- chinamapcolor[i]
      }
    }
    
    NewR <- Counting(newchinamapcolor)
    
    h <- min(1, exp(-(NewR - R)/Temp))
    
    p <- runif(1)  # the random number that is going to help us decide whether to move
    
    if (p < h){
      chinamapcolor <- newchinamapcolor
      
      plot(chinamap, col = chinamapcolor)
      for(n in 1:(nrow(map_crd)-1)){
        points(map_crd[[n,1]],map_crd[[n,2]] , col = "black", pch = as.character(R[n]), lwd = 2)
      }
      points(map_crd[[nrow(map_crd),1]]+1, map_crd[[nrow(map_crd),2]]-1, col = "black", pch = as.character(R[nrow(map_crd)]), lwd = 2)
      legend("topleft", legend = c("total", R[length(R)]), bty = "n")
      
  
      Start.Time<-Sys.time()
      while (Sys.time() < Start.Time+0.1){}
      
      
      R <- NewR # update the record of the function value
    }
    
    #reduce temperature
    Temp<-Temp*(1-TempDecreaseRate)
    if(R[length(R)] == 0){
      break
    }
  }
  
  plot(chinamap, col = chinamapcolor)
  for(n in 1:(nrow(map_crd)-1)){
    points(map_crd[[n,1]],map_crd[[n,2]] , col = "black", pch = as.character(R[n]), lwd = 2)
  }
  points(map_crd[[nrow(map_crd),1]]+1, map_crd[[nrow(map_crd),2]]-1, col = "black", pch = as.character(R[nrow(map_crd)]), lwd = 2)
  legend("topleft", legend = c("total", R[length(R)]), bty = "n")
}

```

```{r}
Startcolor <- numeric()
for(i in 1:nrow(map_crd)){
  Startcolor[i] <- sample(1:4,1)
}
four_color_problem(Startcolor, 10, 0.01, 0.002)
```
