---
title: "TSP"
author: "Chao XIA"
date: "02/24/2019
output: pdf_document
editor_options: 
  chunk_output_type: console
---

## TSP CODE
```{r}
# define a function to calculate the distance between two points and total distance

TotalRoute <- function(Route,Map_Point){
  D <- numeric()
  for (p in 1:(length(Route)-1)){
   D[p] <- dist(rbind(Map_Point[Route[p],],Map_Point[Route[p+1],])) 
  }
  D <- c(D,sum(D))
  return(D)
}
```

```{r}
# define a function to plot map and route
Routeplot <- function(Route,RDS,Map_Point){
  plot(Map_Point, pch = 12)
  points(Map_Point[Route[1],], col = "red", pch = 12)
  legend(Map_Point[Route[1],]-0.25, legend = "SP", bty = "n", cex = 0.75)
  for (p in 1:(length(Route)-1)){
  arrows(x0 = Map_Point[Route[p],1], y0 = Map_Point[Route[p],2], x1 = Map_Point[Route[p+1],1], y1 = Map_Point[Route[p+1],2], angle = 15, length = 0.1)  
  }
  legend("topleft", legend = c("total", round(RDS[length(RDS)],2)), bty = "n", cex = 1)
}
```

```{r}
# define a function to use stimulated annealing to solve TSP
TSP <- function(InitialTemp, FinalTemp, Tempderate){
  
  MP <- read.table(file.choose()) # choose the map information
  
  colnames(MP) <- c("x","y")
  
  # initializing the route
  R <- sample(nrow(MP),nrow(MP))
  R <- c(R,R[1])
  
  # Initializing the temperature, route, route summary and plot
  Temp <- InitialTemp
  RS <- TotalRoute(R,MP)
  Routeplot(R,RS,MP)
  
  # Start SA
  
  while(Temp > FinalTemp){
    
    RS <- TotalRoute(R,MP)
    
    c <- sample(length(R)-1,2)
    
    # get newroute by randomly selet two point and reverse their position
    NewR <- R
    NewR[c[1]:c[2]] <- NewR[c[2]:c[1]]
    NewR[length(NewR)] <- NewR[1]
    
    NewRS <- TotalRoute(NewR,MP)
    
    dE <- NewRS[length(NewRS)] - RS[length(RS)]
    
    h <- min(1, exp(-dE/Temp))
    
    p <- runif(1)
    
    if(p < h){
      R <- NewR
      
      Routeplot(R,RS,MP)
      
      Start.Time<-Sys.time()
      while (Sys.time() < Start.Time+0.1){}
    }
    
    Temp <- Temp * (1 - Tempderate)
  }
  Routeplot(R,RS,MP)
}
```

```{r}
# 10
TSP(10,0.01,0.01)
```

```{r}
# 20
TSP(10,0.01,0.005)
```
```{r}
# 50
TSP(10,0.01,0.002)
```
```{r}
# 100
TSP(10,0.01,0.001)
```

We can see that for more points we need more slow rate to cool down to get the best solution.
